image: php:7.2

pipelines:
  default:
    - step:
         caches:
          - composer
        script:
         - apt-get update && apt-get install -y unzip
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
          - vendor/bin/phpunit
        artifacts:
          - artifact/*
    - step:
        deployment: production
        script:
          - pipe: atlassian/aws-s3-deploy:0.3.7
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: 'us-east-1'
              S3_BUCKET: 'awslaravel'
              EXPIRES: '2022-10-01'
              LOCAL_PATH: 'artifact'
              ACL: 'public-read'
